# Generated by Django 2.2.9 on 2020-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200108_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='decription',
            field=models.TextField(max_length=200),
        ),
    ]
