# Generated by Django 2.2.9 on 2020-01-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200108_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='decription',
            field=models.TextField(max_length=200),
        ),
    ]
