# Generated by Django 2.2.9 on 2020-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200108_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='decription',
            field=models.TextField(),
        ),
    ]
